/** Mirrors backend cancellation-status.js */
export const CANCELLATION_STATUS = {
  REQUESTED: 'REQUESTED',
  COMPLETED: 'COMPLETED',
  REJECTED: 'REJECTED',
};

export const CANCELLATION_STATUS_OPTIONS = [
  CANCELLATION_STATUS.REQUESTED,
  CANCELLATION_STATUS.COMPLETED,
  CANCELLATION_STATUS.REJECTED,
];

export const DEFAULT_CANCELLATION_LIST_LIMIT = 25;

export const MAX_CANCELLATION_LIST_LIMIT = 100;

export const MAX_CANCELLATION_REASON_LENGTH = 1024;
