/** Mirrors backend webhook-subscription-status.js */
export const WEBHOOK_SUBSCRIPTION_STATUS = {
  ACTIVE: 'ACTIVE',
  DISABLED: 'DISABLED',
  DELETED: 'DELETED',
};

export const WEBHOOK_SUBSCRIPTION_STATUS_OPTIONS = [
  WEBHOOK_SUBSCRIPTION_STATUS.ACTIVE,
  WEBHOOK_SUBSCRIPTION_STATUS.DISABLED,
  WEBHOOK_SUBSCRIPTION_STATUS.DELETED,
];

/** Mirrors backend webhook-delivery-status.js */
export const WEBHOOK_DELIVERY_STATUS = {
  PENDING: 'PENDING',
  DELIVERING: 'DELIVERING',
  DELIVERED: 'DELIVERED',
  FAILED: 'FAILED',
  DEAD_LETTERED: 'DEAD_LETTERED',
};

export const WEBHOOK_DELIVERY_STATUS_OPTIONS = [
  WEBHOOK_DELIVERY_STATUS.PENDING,
  WEBHOOK_DELIVERY_STATUS.DELIVERING,
  WEBHOOK_DELIVERY_STATUS.DELIVERED,
  WEBHOOK_DELIVERY_STATUS.FAILED,
  WEBHOOK_DELIVERY_STATUS.DEAD_LETTERED,
];

export const DEFAULT_WEBHOOK_LIST_LIMIT = 25;
